ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS pan_number TEXT,
  ADD COLUMN IF NOT EXISTS pan_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS pan_name TEXT,
  ADD COLUMN IF NOT EXISTS aadhaar_last4 TEXT,
  ADD COLUMN IF NOT EXISTS aadhaar_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS aadhaar_name TEXT,
  ADD COLUMN IF NOT EXISTS kyc_verified_at TIMESTAMP WITH TIME ZONE;
