ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS property_type TEXT,
  ADD COLUMN IF NOT EXISTS bedrooms INTEGER,
  ADD COLUMN IF NOT EXISTS bathrooms INTEGER,
  ADD COLUMN IF NOT EXISTS super_builtup_area INTEGER,
  ADD COLUMN IF NOT EXISTS furnishing TEXT,
  ADD COLUMN IF NOT EXISTS listed_by TEXT,
  ADD COLUMN IF NOT EXISTS floor_no INTEGER,
  ADD COLUMN IF NOT EXISTS total_floors INTEGER,
  ADD COLUMN IF NOT EXISTS parking_slots INTEGER,
  ADD COLUMN IF NOT EXISTS facing TEXT,
  ADD COLUMN IF NOT EXISTS project_name TEXT,
  ADD COLUMN IF NOT EXISTS maintenance_amount INTEGER;